### ISSUE TITLE
Form - Motion To Waive Fees

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/utahexpungements.org#13]
https://www.utcourts.gov/resources/forms/waiver/docs/1301GE_Motion_to_Waive_Fees_and_Statement_Supporting.pdf

**Comment by tuckersamuelsen** [comment]
The form has changed.  This is the form to fill out:
https://www.utcourts.gov/resources/forms/waiver/docs/1301GE_Motion_to_Waive_Fees_and_Statement_Supporting.pdf
