### ISSUE TITLE
Automobile Homicide Flag

### ISSUE THREAD

**Issue by tuckersamuelsen** [JustUtahCoders/utahexpungements.org#135]
Determine if the offense is a Felony Automobile Homicide Flag

**Comment by tuckersamuelsen** [comment]
The statute is anything under 76-5-207.

So the test is 2 parts: (1) Is the severity a felony, and (2) is the statute 76-5-207.

**Comment by Cuthbert20** [comment]
@tuckersamuelsen  Hey Tucker is there a docket that has 76-5-207.  Automobile homicide that I could use for testing?  I went through all the dockets I didn't see one but, I totally could have missed it if there is one.  If not would it be possilbe for you to upload one?  THANKS!

**Comment by tuckersamuelsen** [comment]
@Cuthbert20  yeah, just added Castillo 191909770 to the Dockets folder.  That's one of the charges there.
