### ISSUE TITLE
Form - Petition to Expunge Records for Dismissal or Acquittal

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/utahexpungements.org#15]
Raw form is at https://www.utcourts.gov/howto/expunge/docs/01_Petition_to_Expunge_Records_Criminal-dismissal_or_acquittal.pdf

**Comment by benschinn** [comment]
I can take this one on, if no one is working on it currently. 🙋‍♂️

**Comment by joeldenning** [comment]
No one has taken this one yet! Go for it.

**Comment by benschinn** [comment]
I noticed many of the other form related issues don't have a pdf link. Are those pdf documents to be shared in those issues, or can they be discovered else where?

**Comment by joeldenning** [comment]
Many of the forms can be found at https://bci.utah.gov/expungements/expungement-forms/. All of the forms can be found through google searches or by looking on public utah.gov websites. They're all publicly available

**Comment by benschinn** [comment]
https://github.com/JustUtahCoders/utahexpungements.org/pull/65
