### ISSUE TITLE
Form - Order on Petition to Expunge Records (Dismissal or acquittal)

### ISSUE THREAD

**Issue by benschinn** [JustUtahCoders/utahexpungements.org#180]
https://www.utcourts.gov/howto/expunge/docs/08_Order-dismissal_or_acquittal.pdf

**Comment by Mengqi89** [comment]
In form-list.component.js, I noticed, for some forms, some props (_name_ and _shortDescription_) have used translated text feature but not for other forms. What is the recommendation on how to handle these props?

**Comment by benschinn** [comment]
Great question, it would be better to add translated text. The english portion is of course easy. If you are able to add the Spanish portion we can get eyes on it from either Joe Hoskisson or Joel Denning (I think they both speak Spanish). 

You can find the en.js and es.js here:
https://github.com/JustUtahCoders/utahexpungements.org/tree/master/frontend/i18n

**Comment by Mengqi89** [comment]
I am almost done with this issue. I just need help with the following two items:

1. Description of the form @tuckersamuelsen 
2. Spanish translation (this probably can be done altogether later?)

**Comment by tuckersamuelsen** [comment]
For this form:

The top left section (Name, Address, etc down to Email) should be filled out with the same information as on the other forms for their case.

Petitioner Name should be the same as the person's name.

Judge and Case Number will be the same as for the other forms within the same case.

Do NOT check the box at all for "Pleadings and Papers" or the section for hearings.

Do NOT check the box under section 3.

Sections 5 and 6, the case number is just the same case number for the case.

Hope this helps!

**Comment by Mengqi89** [comment]
Tucker, thanks for the response. I should have been more clear. See beneath. 
<img width="179" alt="Screen Shot 2020-04-21 at 1 52 56 PM" src="https://user-images.githubusercontent.com/43308423/79907992-bd93aa80-83d7-11ea-8f0d-91aaf24fe1a2.png">
<img width="179" alt="Screen Shot 2020-04-21 at 1 53 03 PM" src="https://user-images.githubusercontent.com/43308423/79908006-c2585e80-83d7-11ea-9d33-87360ebf8c0a.png">

**Comment by tuckersamuelsen** [comment]
Oh sorry.  Let's go with:

A form you file with the courts along with your expungement petition if your case was dismissed or acquitted.

**Comment by benschinn** [comment]
https://github.com/JustUtahCoders/utahexpungements.org/pull/181
