### ISSUE TITLE
Form Bank Issues

### ISSUE THREAD

**Issue by benschinn** [JustUtahCoders/utahexpungements.org#183]
_"Hey all - just had a call with Tucker and the expungement navigator, Jake. It was super cool. Jake has actually been using the form bank portion of the site for several weeks.
In doing that, he’s come up with a handful of issues to address. If we can address them, it’s possible that Tucker’s company will link (or embed, etc) to our site. Which would be awesome for driving some traffic and potentially making a bigger impact."_ - Luke

To help with addressing the issues below, please follow these steps:
1. If you are actively taking on the issue please check the box.
2. Once your PR to address the issue has been merged in please do ~~strikethrough~~ on the issue and reference your MR link that addresses it. 

#### Issues:

2. - [x] ~~Can we remove the dates from the signature line being populated, so that they have to sign the date as well as their signature and location.~~ https://github.com/JustUtahCoders/utahexpungements.org/pull/186 https://github.com/JustUtahCoders/utahexpungements.org/pull/198
   1. - [x] ~~On the court address population for West Valley, its coming up as 3590 South 2700 West West Valley, UT. Let’s get a comma in between the city and the street addresses.~~ https://github.com/JustUtahCoders/utahexpungements.org/pull/185

3. - [x] ~~When I move to do the coversheet, it is not allowing me to input the defendant/respondent.~~ https://github.com/JustUtahCoders/utahexpungements.org/pull/190

4. - [x] ~~Also, there is a separate cover sheet for justice court cases, this is only allowing district court case.~~ https://github.com/JustUtahCoders/utahexpungements.org/pull/182

5. - [x] ~~Finally, on the district court case, the box “This case is exempt for URCP 26” needs to be checked o page one.~~ https://github.com/JustUtahCoders/utahexpungements.org/pull/193

6. - [x] ~~Phone number not populating from each form. Have to enter phone number each time. Ok wait, seems to only be the Order form and the Cover Sheet form.~~ https://github.com/JustUtahCoders/utahexpungements.org/pull/194

7. - [x] ~~REMOVE the check box on the Expungement Orders for whether the matter is being resolved by pleading or by hearing. The Judge will check that box. It is too early to tell. A hearing will be held if a victim or prosecutor objects. We don’t know if that is going to happen when we submit this form.~~  https://github.com/JustUtahCoders/utahexpungements.org/pull/197

8. - [x] ~~NEED Consent and Waiver of Hearing form put on site ASAP. This is needed in all cases. It does not need to be populated with the attorneys info, the specific attorneywill fill in the box themselves.~~ https://github.com/JustUtahCoders/utahexpungements.org/pull/195

9. - [x] ~~Order on Motion to Waive Fees info not populating over from other docs.~~ https://github.com/JustUtahCoders/utahexpungements.org/issues/183

10. - [x] ~~Petitioner not populating on Order on Motion to Waive Fees, change defendant to Respondent.~~ https://github.com/JustUtahCoders/utahexpungements.org/issues/183

11. - [x] When printing petition, some sort of reminder to print two copies, one for the court, one for the prosecutor. https://github.com/JustUtahCoders/utahexpungements.org/pull/199

12. - [x] ~~Sandy City Justice Court is populating as 210 W Sego Lily DriveAttorney Filings1. - Sandy, UT 84070~~ https://github.com/JustUtahCoders/utahexpungements.org/pull/185

13. - [x] ~~No Order on Petition to Expunge Dismissal or Acquittal available~~ https://github.com/JustUtahCoders/utahexpungements.org/pull/181

14. - [x] ~~Phone number not auto populating from form to form for order to waive fees from petition to expunge dismissal~~ https://github.com/JustUtahCoders/utahexpungements.org/pull/194

15. - [x] ~~Petitioner name not populating onto finished Order to Waive Fees in Petitioner v. Respondent area~~ https://github.com/JustUtahCoders/utahexpungements.org/issues/183

16. - [x] ~~Consent and Waiver of Hearing Page 2 is the same as Page 1, need real page 2~~ https://github.com/JustUtahCoders/utahexpungements.org/pull/181

17. - [x] ~~On Orders, the box “the pleadings and other papers of the parties” needs to stop being checked. It needs to be blank.~~
https://github.com/JustUtahCoders/utahexpungements.org/pull/191 https://github.com/JustUtahCoders/utahexpungements.org/pull/197

18. - [ ] When I click the box Justice Court each time starting a new petition, the screen goes blank. When I refresh, it takes me back to my very first Fake case for Jake Smith, not the current client. 

Original feedback from Jake:
[Form Software Issues.docx](https://github.com/JustUtahCoders/utahexpungements.org/files/4552773/Form.Software.Issues.docx)

**Comment by lukeschunk** [comment]
nice thanks for making this issue!

**Comment by Mengqi89** [comment]
@tuckersamuelsen  Regarding item 3, I noticed the **defendant/respondent** in [a separate form](https://www.utcourts.gov/resources/forms/waiver/docs/1302GE_Order_on_Motion_to_Waive_Fees.pdf) has a placeholder of "State of Utah". Do you want me to maintain that placeholder for **defendant/respondent** in district and justice court cover sheets?

`<TextInput
        dataKey="case.defendant"
        label={__("defendant")}
        placeholder="State of Utah"
      />`

**Comment by Mengqi89** [comment]
Can someone give an example of the following issue?

> On Orders, the box “the pleadings and other papers of the parties” needs to stop being checked. It needs to be blank.

**Comment by benschinn** [comment]
> Can someone give an example of the following issue?
> 
> > On Orders, the box “the pleadings and other papers of the parties” needs to stop being checked. It needs to be blank.

It seems like Jake is talking about this form:
https://utahexpungements.org/app/forms/order-on-motion-for-reduction-of-conviction

If you look at section 3, _Matter_, there's a drop down. If you select _"the pleadings and other papers of the parties"_ then it checks the box. It sounds like this behavior needs to be disabled, where we do not allow the user to check that box. The best way to achieve this is probably to remove the option here: 
https://github.com/JustUtahCoders/utahexpungements.org/blob/master/frontend/app/forms/order-on-motion-for-reduction-of-conviction/order-on-motion-for-reduction-of-conviction.web.component.js#L19

**Comment by Mengqi89** [comment]
Item 4 here is issue https://github.com/JustUtahCoders/utahexpungements.org/issues/179

**Comment by Mengqi89** [comment]
I am working on 3, 8 and 17.

**Comment by oliviaclyde** [comment]
I am working on 7

**Comment by Mengqi89** [comment]
Issue 3, 8 and 17 are resolved, pending code reviews and merges.

**Comment by Mengqi89** [comment]
I believe issue 14 is fixed https://github.com/JustUtahCoders/utahexpungements.org/pull/194

**Comment by benschinn** [comment]
> Issue 16 is fixed.

what PR addresses item 16?

**Comment by Mengqi89** [comment]
> > Issue 16 is fixed.
> 
> @Mengqi89 what PR addressed item 16?

It's [here](https://github.com/JustUtahCoders/utahexpungements.org/pull/181/commits/2439d3cdb5a85cabe67e8ceef89d06b3713e1ffe). It was fixed a while ago.

**Comment by Mengqi89** [comment]
Issue 4 is PR https://github.com/JustUtahCoders/utahexpungements.org/pull/182
Issue 8 is PR https://github.com/JustUtahCoders/utahexpungements.org/pull/195

**Comment by Mengqi89** [comment]
I am working on 9, 10 and 15.

**Comment by Mengqi89** [comment]
@tuckersamuelsen  I cannot seem to replicate issue 18. Can you please take a point and clarify what the issue looks like? Thanks!

**Comment by oliviaclyde** [comment]
I think issue 8 has been resolved and can be ~~crossed off~~. @Mengqi89 can you confirm?

**Comment by Mengqi89** [comment]
> I think issue 8 has been resolved and can be ~crossed off~. @Mengqi89 can you confirm?

Yes, it's resolved.

**Comment by oliviaclyde** [comment]
I'm having trouble replicating issue 18. Anyone seeing this occur?

**Comment by benschinn** [comment]
I will be working on number 11. there are several ways to solve this problem. we could have a tooltip, we could have a pop up or toast UI, we could use the good old alert function. let me know if someone wants to pair on this. I will likely work on this tonight or tomorrow sometime.

**Comment by oliviaclyde** [comment]
@benschinn I'd love to pair on this and learn something new. I'll make myself available whenever you plan to work on it.
