### ISSUE TITLE
Form - Draft a Court Order (Drug Conviction)

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/utahexpungements.org#24]
https://www.utcourts.gov/howto/expunge/docs/08_Order-drug_possession.pdf

**Comment by tuckersamuelsen** [comment]
For this form:

1. Fill out the top left corner with the petitioner's information. 
2. Fill in the court location information with Sean's table.
3. Fill in petitioner name and case number.  Judge name may not be necessary.
4. Check the box by "The pleadings and papers..."
5. Under section 5, put in the same case number as above.
6. Under section 6 put in the same case number.
