### ISSUE TITLE
Form - Coversheet

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/utahexpungements.org#25]
https://www.utcourts.gov/resources/forms/civil/Civil_Filing_Cover_Sheet.pdf

**Comment by lukeschunk** [comment]
@tuckersamuelsen  on this form the "Defendent/respondant" portion - who is that referring to? 

In our data we have "person" and I was assuming that was the petitioner; I'm not sure if we have the concept of the "defendant/respondant" in our system yet.

**Comment by lukeschunk** [comment]
See what I have so far - let me know what else needs to be filled out: 

<img width="530" alt="Screen Shot 2019-09-17 at 7 55 03 PM" src="https://user-images.githubusercontent.com/13579578/65100636-587d5f80-d985-11e9-85ef-5ad5af565008.png">
<img width="524" alt="Screen Shot 2019-09-17 at 7 55 11 PM" src="https://user-images.githubusercontent.com/13579578/65100637-587d5f80-d985-11e9-82ff-b6f725c9a349.png">

**Comment by tuckersamuelsen** [comment]
I like this but I think it might be useful to have a radio before the Attorney part.  Basically just ask if an attorney is filling it out for them, and if they say yes than ask for attorney name and bar number.  I can see it being confusing if a person is on their own, not knowing what to put.

What do you think?

**Comment by lukeschunk** [comment]
That sounds good - we can only include the attorney name and bar number if it's an attorney filling out the form. We already have similar radio-button style logic in other forms 👍

**Comment by seanbw89** [comment]
Fixed here #56 & #90
