### ISSUE TITLE
Form - Court Order for Waiving Fees

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/utahexpungements.org#28]
https://www.utcourts.gov/resources/forms/waiver/docs/1302GE_Order_on_Motion_to_Waive_Fees.pdf

**Comment by jenseng** [comment]
What should we put as the description for this form? Since it's the court's order on the motion, and not the motion itself, maybe something like: "A form you file with the courts so the judge can rule on your motion to waive fees" ?

**Comment by joeldenning** [comment]
Yeah that description sounds good. Maybe clarify “file with your expungement petition.”

My understanding is that you file about 5 forms all together in one go:

- certificate of eligibility
- petition
- court order for petition
- motion for fees
- court order for fees

I think Tucker sometimes calls all those forms together an “expungement forms packet” or something similar.
