### ISSUE TITLE
Add expungement clinic info to our website

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/utahexpungements.org#6]

**Comment by joeldenning** [comment]
From Noella:

>I think we should definitely include some information about the U of U’s monthly expungement clinic:
>
>Expungement Free Legal Clinic
>
>Area of Law: Impediments to employment, such as expungements and addressing issues regarding outstanding warrants.
>When: 1st Thursday of every month. Closed July 5.
>Time: 5 pm – 6:00 pm (Please plan to arrive no later than 6 pm otherwise you will have to wait until the following month).
>Location: LDS Employment Center. 780 West 800 South in Salt Lake City.
>Sponsored by: S.J. Quinney College of Law and Utah Legal Services.

**Comment by Cuthbert20** [comment]
I created another overview landing 7 in en.js and rendered it in landing.component.js. I was wondering though do we want to include a link to the event? If so this is the only url I could find that references the event, the problem being it also references other free legal clinics.  I didn't know if it would be to confusing for a user.
I was just wondering if I could get your opinion on the url, ie if I should include the link or not.

url: 
https://law.utah.edu/pro-bono-initiative/free-legal-clinics/


Thanks!

**Comment by joeldenning** [comment]
Resolved in https://github.com/JustUtahCoders/utahexpungements.org/pull/91
