### ISSUE TITLE
rem css issue

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/utahexpungements.org#61]
In some browsers the app looks huge sometimes. It is because we have one rem set to one pixel. We should change it to just leave the browser default in place of one rem set to 16px.

This will requiring updating all css in all components to use the new rem size.

**Comment by HappyViki** [comment]
Is this still an issue? Can you share which browsers, pages, and screenshots of where it's happening?

I want to work on this.

**Comment by joeldenning** [comment]
Yes -- on Firefox and Chrome intermittently the browser is completely the wrong size. Most recently @kthompson55 was seeing this on his machine.

To fix it, delete this line of code:

https://github.com/JustUtahCoders/utahexpungements.org/blob/8e040d8b8e7f9a4c50d8bbb506a819257976ade1/frontend/styleguide.js#L29

That will change the font size for the root element, which determines the size of the `rem` unit. Next go through all the css in all of the app -- wherever `rem` is used you need to multiple by 16 since the default size for `rem` if left unspecified is `16px`. Check out the `rem` unit [on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/length) where it describes how 16px is the common unit for rems.

**Comment by Cuthbert20** [comment]
Hi, I know the issue was already fixed but, I was thinking what if we just set font-size to a percent so assuming 100% is 16px and we wanted 1px to be our default font-size so we can use rem for margin or padding to make media queries easier we could set font-size to 1 divided by 16 (6.25%). That way we can still use rem's for styling and the user could change the size of the font in their browser.  
I just thought it might be a faster fix but, I could be wrong.  :)

**Comment by joeldenning** [comment]
> what if we just set font-size to a percent so assuming 100% is 16px and we wanted 1px to be our default font-size so we can use rem for margin or padding to make media queries easier we could set font-size to 1 divided by 16 (6.25%)

The problem is that browsers don't like it when you set the root font size so small. Chrome sometimes refuses to respect that font-size and then the app looks weird. The code currently already does set the font size that small, and it doesn't work in all browsers.

**Comment by joeldenning** [comment]
This was fixed in #81
